### ISSUE TITLE
stateofjs.com Js reports

### ISSUE THREAD

**Issue by vicvinc** [alienzhou/frontend-tech-list#3]
How can I get a password of 2018.stateofjs.com and read the report?

**Comment by vicvinc** [comment]
the site is not officially launched yet. It should be ready in a few days.

--from one of the authors at stateofjs.com

**Comment by AlphaCodeZero** [comment]
UPDATE: It has been launched.

**Comment by alienzhou** [comment]
> the site is not officially launched yet. It should be ready in a few days.
> 
> --from one of the authors at stateofjs.com

@vicvinc thanks for feedback
It has been launched now.
